package com.cleanwise.service.api.process.operations;

import com.cleanwise.service.api.APIAccess;
import com.cleanwise.service.api.session.Order;
import com.cleanwise.service.api.value.*;
import com.cleanwise.service.api.process.operations.DocBuilder;
import java.io.BufferedOutputStream;
import java.io.FileOutputStream;
import java.io.File;
import java.util.ArrayList;
import java.util.Iterator;
import javax.naming.NamingException;
import com.cleanwise.service.api.APIServiceAccessException;
import java.rmi.RemoteException;
import com.cleanwise.view.utils.ShopTool;
import java.text.NumberFormat;
import java.math.BigDecimal;
import com.cleanwise.service.api.util.RefCodeNames;
/* This class can be used as Generator for Kohls Order Confirmation Notificaton E-mail
/*  If e-mail shoud be generated by this class it name (with it's package) must be
/*  defined as property value for the property code = "CONFIRM_ORDER_EMAIL_GENERATOR"
*/
public class OrderNotificationGeneratorKohlsC extends OrderNotificationGeneratorKohlsHtml  {

    private static final String className = "OrderNotificationGeneratorKohlsC";
    private String title = CONFIRM;
    private String subNote = "to confirm the order you have just placed with us.";

    public void writeHeaderTXT(StringBuffer sb, OrderInfoDataView orderInfo) {
        super.writeHeaderTXT(sb, orderInfo, subNote, title);
    }

    public String getSubject(Object data){
    	return getSubject(data, CONFIRM);
    }

 }

