package com.cleanwise.service.api.process.operations;

import com.cleanwise.service.api.APIAccess;
import com.cleanwise.service.api.session.Order;
import com.cleanwise.service.api.value.*;
import com.cleanwise.service.api.process.operations.DocBuilder;
import java.io.BufferedOutputStream;
import java.io.FileOutputStream;
import java.io.File;
import java.util.ArrayList;
import java.util.Iterator;
import javax.naming.NamingException;
import com.cleanwise.service.api.APIServiceAccessException;
import java.rmi.RemoteException;
import com.cleanwise.view.utils.ShopTool;
import java.text.NumberFormat;
import java.math.BigDecimal;
import com.cleanwise.service.api.util.RefCodeNames;
/* This class can be used as Generator for Kohls Order Pending Approval Notificaton E-mail
/*  If e-mail shoud be generated by this class it name (with it's package) must be
/*  defined as property value for the property code = "PENDING_APPROV_EMAIL_GENERATOR"
*/

public class OrderNotificationGeneratorKohlsPA extends OrderNotificationGeneratorKohlsHtml  {

    private static final String className = "OrderNotificationGeneratorKohlsPA";
    private String title = APPROVAL;
    private String subNote = "to inform you this order requires your approval.";

    public void writeHeaderTXT(StringBuffer sb, OrderInfoDataView orderInfo) {
        super.writeHeaderTXT(sb, orderInfo, subNote, title);
    }

    public String getSubject(Object data){
    	return getSubject(data, APPROVAL);
    }

    public static void main (String argv[]) {   //for test
        try {
        	OrderNotificationGeneratorKohlsPA generator = new OrderNotificationGeneratorKohlsPA();
        	generator.getAPIAccess();
            
            generator.generate(new Integer(1354456),"c:\\temp\\order_");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

 }

