#!/bin/sh

lcmd=daily_order_reprocess

## common for all scripts
lockfile=/tmp/xsuite.lock.$lcmd
if [ -f $lockfile ]
then
  echo "error lock on for $lcmd"
  exit
fi


echo "--- PID $$ " > $lockfile

#cd ${XSUITE_HOME}
#. .profile

. ../app.sh.env
cd ../util

tstamp=`date '+Date-%Y.%m.%d-Time-%H.%M.%S'`
logfile="../reports/$tstamp.$0.log"

echo "--- PID $$ " > $logfile
sh appcmd.sh -Dcmd=$lcmd -DmaxRows=-1 >> $logfile 2>&1
echo "--- PID $$ done " >> $logfile

cat $logfile

rm $lockfile

