#!/bin/sh

lcmd=event_sys_job

## common for all scripts

lockfile=/tmp/xsuite.lock.$lcmd 
if [ -f $lockfile ]
then
  echo "lock on for $lcmd"
  exit
fi

echo $$ > $lockfile

. ../app.sh.env
cd ../util


tstamp=`date '+Date-%Y.%m.%d-Time-%H.%M.%S'`
logfile="../reports/$tstamp.$0.log"

echo "--- PID $$ " > $logfile
sh appcmd.sh -Dcmd=$lcmd >> $logfile 2>&1
echo "--- PID $$ done " >> $logfile

rm $lockfile

