#!/bin/sh

lcmd=orders_to_lawson

## common for all scripts

lockfile=/tmp/xsuite.$USER.lock.$lcmd 
if [ -f $lockfile ]
then
  echo "error lock on for $lcmd"
  exit
fi


echo $$ > $lockfile

. ../app.sh.env
cd ${XSUITE_HOME}/xsuite/util


tstamp=`date '+Date-%Y.%m.%d-Time-%H.%M.%S'`
logfile="../reports/$tstamp.$0.log"

echo "--- PID $$ " > $logfile
sh appcmd.sh -Dcmd=$lcmd -Dstores=all
echo "--- PID $$ done " >> $logfile

rm $lockfile

