#!/bin/sh

## common for all scripts

lockfile=/tmp/xsuite.lock.xsuite-load-address-validation-data
if [ -f $lockfile ]
then
  echo "lock on for xsuite-load-address-validation-data"
  exit
fi

echo $$ > $lockfile

cd ${XSUITE_HOME}
. .profile
cd $XDIR/util

tstamp=`date '+Date-%Y.%m.%d-Time-%H.%M.%S'`
logfile="../reports/$tstamp.load-address-validation-data.log"
echo "--- PID $$ " > $logfile

## Note that the crimson.jar file must be placed at the end
## of the classpath list.

java -Xmx512m -classpath "${TJCPATH}" \
 -Dconf="${XSUITE_HOME}/xsuite/app.properties" \
com.cleanwise.service.apps.loaders.VertexDBFZipcodeLoader | tee ${logFile}


echo "--- PID $$ done " >> $logfile

rm $lockfile
