#!/bin/sh

lcmd=invoices_to_lawson

## common for all scripts

lockfile=/tmp/xsuite.$USER.lock.$lcmd
if [ -f $lockfile ]
then
  echo "error lock on for $lcmd"
  exit
fi

echo $$ > $lockfile

. ../app.sh.env
# the sqlplus client does not support this env variable
unset NLS_LANG

cd $XDIR/util

tstamp=`date '+Date-%Y.%m.%d-Time-%H.%M.%S'`
logfile="../reports/$tstamp.$0.log"

echo "--- PID $$ " > $logfile
sh appcmd.sh -Dcmd=$lcmd >> $logfile 2>&1
echo "--- PID $$ done " >> $logfile

rm $lockfile
