/*
 * FaxException.java
 *
 * Created on April 30, 2002, 11:29 AM
 */

package com.cleanwise.view.utils.fax;

/**
 * Wrapper for any fax exception generated by either the API that talks to the fax server, or 
 * any internal exceptions that are generated during sending or construction of a fax document.
 * @author  bstevens
 */
public class FaxException extends java.lang.Exception {

    /**
     * Creates a new instance of <code>FaxException</code> without detail message.
     */
    public FaxException() {
    }


    /**
     * Constructs an instance of <code>FaxException</code> with the specified detail message.
     * @param msg the detail message.
     */
    public FaxException(String msg) {
        super(msg);
    }
}


