delete CLW_INVENTORY_LEVEL_DETAIL;

INSERT INTO CLW_INVENTORY_LEVEL_DETAIL  (INVENTORY_LEVEL_DETAIL_ID,INVENTORY_LEVEL_ID,PERIOD,CLW_VALUE,ADD_DATE,ADD_BY,MOD_DATE,MOD_BY)

Select CLW_INVENTORY_LEVEL_DETAIL_SEQ.nextval,INVENTORY_LEVEL_ID,PERIOD,PAR_VALUE,ADD_DATE,ADD_BY,MOD_DATE,MOD_BY from

(SELECT INVENTORY_LEVEL_ID,1 AS PERIOD,PAR_VALUE1 AS PAR_VALUE,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_INVENTORY_LEVEL
union
SELECT INVENTORY_LEVEL_ID,2 AS PERIOD,PAR_VALUE2 AS PAR_VALUE,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_INVENTORY_LEVEL
union
SELECT INVENTORY_LEVEL_ID,3 AS PERIOD,PAR_VALUE3 AS PAR_VALUE,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_INVENTORY_LEVEL
union
SELECT INVENTORY_LEVEL_ID,4 AS PERIOD,PAR_VALUE4 AS PAR_VALUE,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_INVENTORY_LEVEL
union
SELECT INVENTORY_LEVEL_ID,5 AS PERIOD,PAR_VALUE5 AS PAR_VALUE,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_INVENTORY_LEVEL
union
SELECT INVENTORY_LEVEL_ID,6 AS PERIOD,PAR_VALUE6 AS PAR_VALUE,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_INVENTORY_LEVEL
union
SELECT INVENTORY_LEVEL_ID,7 AS PERIOD,PAR_VALUE7 AS PAR_VALUE,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_INVENTORY_LEVEL
union
SELECT INVENTORY_LEVEL_ID,8 AS PERIOD,PAR_VALUE8 AS PAR_VALUE,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_INVENTORY_LEVEL
union
SELECT INVENTORY_LEVEL_ID,9 AS PERIOD,PAR_VALUE9 AS PAR_VALUE,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_INVENTORY_LEVEL
union
SELECT INVENTORY_LEVEL_ID,10 AS PERIOD,PAR_VALUE10 AS PAR_VALUE,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_INVENTORY_LEVEL
union
SELECT INVENTORY_LEVEL_ID,11 AS PERIOD,PAR_VALUE11 AS PAR_VALUE,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_INVENTORY_LEVEL
union
SELECT INVENTORY_LEVEL_ID,12 AS PERIOD,PAR_VALUE12 AS PAR_VALUE,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_INVENTORY_LEVEL
union
SELECT INVENTORY_LEVEL_ID,13 AS PERIOD,PAR_VALUE13 AS PAR_VALUE,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_INVENTORY_LEVEL);
