create table CLW_COST_CENTER_RULE_DETAIL (
  COST_CENTER_RULE_DETAIL_ID NUMBER(38) not null,
  COST_CENTER_RULE_ID NUMBER(38) not null,
  PARAM_NAME VARCHAR2(30),
  PARAM_VALUE VARCHAR2(255),
  ADD_DATE DATE not null,
  ADD_BY VARCHAR2(30) null,
  MOD_DATE DATE not null,
  MOD_BY VARCHAR2(30) null,
  constraint CLW_COST_CENTER_RULE_DETAIL_PK primary key (COST_CENTER_RULE_DETAIL_ID)
);