create table CLW_COST_CENTER_RULE (
  COST_CENTER_RULE_ID NUMBER(38) not null,
  BUS_ENTITY_ID NUMBER(38),
  COST_CENTER_ID NUMBER(38),
  CATEGORY_ID NUMBER(38),
  MATCH_TYPE_CD VARCHAR(30),
  EFF_DATE DATE,
  ADD_DATE DATE not null,
  ADD_BY VARCHAR2(30) null,
  MOD_DATE DATE not null,
  MOD_BY VARCHAR2(30) null,
  constraint CLW_COST_CENTER_RULE_PK primary key (COST_CENTER_RULE_ID)
);