INSERT INTO CLW_FISCAL_CALENDER_DETAIL  (FISCAL_CALENDER_DETAIL_ID,FISCAL_CALENDER_ID,PERIOD,MMDD,ADD_DATE,ADD_BY,MOD_DATE,MOD_BY)

Select CLW_FISCAL_CALENDER_DETAIL_SEQ.nextval,FISCAL_CALENDER_ID,PERIOD,MMDD,ADD_DATE,ADD_BY,MOD_DATE,MOD_BY from

(SELECT FISCAL_CALENDER_ID,1 AS PERIOD,MMDD1 AS MMDD,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_FISCAL_CALENDER
union
SELECT FISCAL_CALENDER_ID,2 AS PERIOD,MMDD2 AS MMDD,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_FISCAL_CALENDER
union
SELECT FISCAL_CALENDER_ID,3 AS PERIOD,MMDD3 AS MMDD,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_FISCAL_CALENDER
union
SELECT FISCAL_CALENDER_ID,4 AS PERIOD,MMDD4 AS MMDD,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_FISCAL_CALENDER
union
SELECT FISCAL_CALENDER_ID,5 AS PERIOD,MMDD5 AS MMDD,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_FISCAL_CALENDER
union
SELECT FISCAL_CALENDER_ID,6 AS PERIOD,MMDD6 AS MMDD,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_FISCAL_CALENDER
union
SELECT FISCAL_CALENDER_ID,7 AS PERIOD,MMDD7 AS MMDD,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_FISCAL_CALENDER
union
SELECT FISCAL_CALENDER_ID,8 AS PERIOD,MMDD8 AS MMDD,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_FISCAL_CALENDER
union
SELECT FISCAL_CALENDER_ID,9 AS PERIOD,MMDD9 AS MMDD,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_FISCAL_CALENDER
union
SELECT FISCAL_CALENDER_ID,10 AS PERIOD,MMDD10 AS MMDD,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_FISCAL_CALENDER
union
SELECT FISCAL_CALENDER_ID,11 AS PERIOD,MMDD11 AS MMDD,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_FISCAL_CALENDER
union
SELECT FISCAL_CALENDER_ID,12 AS PERIOD,MMDD12 AS MMDD,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_FISCAL_CALENDER
union
SELECT FISCAL_CALENDER_ID,13 AS PERIOD,MMDD13 AS MMDD,sysdate AS ADD_DATE,'achickin' AS ADD_BY,sysdate AS MOD_DATE,'achickin' AS MOD_BY from CLW_FISCAL_CALENDER);
