drop table CLT_POLLOCK_CATALOG_ASSOC;
CREATE GLOBAL TEMPORARY TABLE CLT_POLLOCK_CATALOG_ASSOC
(
  VERSION          VARCHAR2(5 BYTE),
  STORE_ID         VARCHAR2(20 BYTE),
  STORE_NAME       VARCHAR2(255 BYTE),
  ACCOUNT_REF_NUM  VARCHAR2(255 BYTE),
  ACCOUNT_NAME     VARCHAR2(100 BYTE),
  SITE_NAME        VARCHAR2(255 BYTE),
  SITE_REF_NUM     VARCHAR2(100 BYTE),
  CATALOG_KEY      VARCHAR2(100 BYTE),
  PRICE_LIST_1     VARCHAR2(100 BYTE),
  PRICE_LIST_2     VARCHAR2(100 BYTE),
  PROPRIETARY_LIST VARCHAR2(100 BYTE),
  BUY_LIST         VARCHAR2(100 BYTE),
  ADD_BY           VARCHAR2(40 BYTE),
  ADD_DATE         DATE
)
ON COMMIT DELETE ROWS
NOCACHE;