UPDATE CLW_ORDER_ITEM_ACTION IA SET STATUS = 'T855_SENT X'
WHERE IA.ACTION_CD like 'ACK %' 
AND ORDER_ID IN (
  SELECT ORDER_ID FROM CLW_ORDER O 
  WHERE O.ORDER_ID = IA.ORDER_ID
  AND O.ACCOUNT_ID IN (SELECT BUS_ENTITY_ID FROM CLW_TRADING_PARTNER_ASSOC WHERE TRADING_PARTNER_ID = 1)
);