
DROP TABLE CLT_POLLOCK_SITE_LOADER CASCADE CONSTRAINTS;

CREATE GLOBAL TEMPORARY TABLE CLT_POLLOCK_SITE_LOADER
(
  VERSION                  VARCHAR2(10 BYTE),
  ACTION                   VARCHAR2(2 BYTE),
  STORE_ID                 VARCHAR2(10 BYTE),
  STORE_NAME               VARCHAR2(255 BYTE),
  ACCOUNT_REF_NUM          VARCHAR2(255 BYTE),
  ACCOUNT_NAME             VARCHAR2(255 BYTE),
  CURRENT_ACCOUNT_ID	   VARCHAR2(10 BYTE),
  NEW_ACCOUNT_ID	   VARCHAR2(10 BYTE),
  SITE_ID		   VARCHAR2(10 BYTE),
  SITE_NAME                VARCHAR2(255 BYTE),
  SITE_REF_NUM             VARCHAR2(255 BYTE),
  TAXABLE                  VARCHAR2(10 BYTE),
  INVENTORY_SHOPPING_PARA  VARCHAR2(10 BYTE),
  BUYER_ORDER_GUIDE        VARCHAR2(255 BYTE),
  FIRST_NAME               VARCHAR2(255 BYTE),
  LAST_NAME                VARCHAR2(255 BYTE),
  ADDRESS1                 VARCHAR2(255 BYTE),
  ADDRESS2                 VARCHAR2(255 BYTE),
  ADDRESS3                 VARCHAR2(255 BYTE),
  ADDRESS4                 VARCHAR2(255 BYTE),
  CITY                     VARCHAR2(255 BYTE),
  STATE                    VARCHAR2(255 BYTE),
  POSTAL_CODE              VARCHAR2(10 BYTE),
  COUNTRY                  VARCHAR2(255 BYTE),
  SHIP_MESSAGE             VARCHAR2(255 BYTE),
  ORDER_GUIDE_COMMENTS     VARCHAR2(255 BYTE),
  item_display_restrict    VARCHAR2(255 BYTE),
  ADD_BY                   VARCHAR2(30 BYTE),
  ADD_DATE                 DATE
)
ON COMMIT DELETE ROWS
NOCACHE;

