ALTER TABLE RPT_REPORT_USER_ACTIVITY ADD (
    SERVER_NAME VARCHAR2(30)
);
ALTER TABLE RPT_REPORT_USER_ACTIVITY ADD (
    REQUEST_ID VARCHAR2(30)
);
CREATE INDEX 
    STJOHN_LOCAL.RPT_REPORT_USER_ACTIVITY_I1 
ON 
    STJOHN_LOCAL.RPT_REPORT_USER_ACTIVITY (SESSION_ID);