CREATE TABLE DL_SCHEDULES ( 
  SCHEDULE_ID NUMBER(38,0) NOT NULL,
  SCHEDULE_NAME VARCHAR2(30 CHAR),
  ORDER_DATE VARCHAR2(30 CHAR),
  ORDER_TIME VARCHAR2(30 CHAR),
  SCHEDULE_DETAIL_CD VARCHAR2(30 CHAR),
  SCHEDULE_DETAIL_ID NUMBER(38,0),
  SITE_NAME VARCHAR2(255 CHAR),
  SITE_ID NUMBER,
  ACCOUNT_ID NUMBER(38,0),
  STORE_ID NUMBER(38,0),
  SCHEDULE_RULE_CD VARCHAR2(30 CHAR),
  CLW_VALUE VARCHAR2(4000 CHAR),
  ADD_DATE DATE
)  
/ 


CREATE TABLE DL_INV_CART ( 
  SCH_DATE VARCHAR2(10 BYTE),
  SCH_TIME VARCHAR2(5 BYTE),
  SITE_ID NUMBER(38,0),
  ORDER_GUIDE_ID NUMBER(38,0),
  CATALOG_ID NUMBER(38,0),
  ITEM_ID NUMBER(38,0),
  QUANTITY NUMBER(6,0),
  ADD_DATE DATE
)
/ 