CREATE INDEX clw_catalog_structure_iku ON clw_catalog_structure (catalog_id, item_id);
 
DROP TABLE CLT_NSC_CATEGORY_SORT_ORDER1 CASCADE CONSTRAINTS;
 
CREATE GLOBAL TEMPORARY TABLE CLT_NSC_CATEGORY_SORT_ORDER1
(
  STORE_ID           NUMBER (38) NOT NULL,
  STORE_CATALOG_ID   NUMBER (38) NOT NULL,
  CATEGORY_ID     NUMBER (38) NOT NULL,
  SORT_ORDER    NUMBER(10),
  CATALOG_ID    NUMBER (38) NOT NULL,
  CATALOG_STRUCTURE_ID    NUMBER (38) NOT NULL,
  CATALOG_SORT_ORDER NUMBER (10)
 )
ON COMMIT DELETE ROWS
NOCACHE;