package com.johnsondiversey.msds.msdswebservice.jdimsds;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * JohnsonDiversey Material Safety Data Sheet(MSDS) Web Services
 *
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-06T17:33:59.263-04:00
 * Generated source version: 2.6.0
 * 
 */
@WebServiceClient(name = "JohnsonDiversey_x0020_MSDS_x0020_Web_x0020_Services", 
                  wsdlLocation = "http://msds.diversey.com/MSDSWebService/jdimsds.asmx?WSDL",
                  targetNamespace = "http://msds.johnsondiversey.com/MSDSWebService/JDIMSDS") 
public class JohnsonDiverseyX0020MSDSX0020WebX0020Services extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://msds.johnsondiversey.com/MSDSWebService/JDIMSDS", "JohnsonDiversey_x0020_MSDS_x0020_Web_x0020_Services");
    public final static QName JohnsonDiverseyX0020MSDSX0020WebX0020ServicesSoap = new QName("http://msds.johnsondiversey.com/MSDSWebService/JDIMSDS", "JohnsonDiversey_x0020_MSDS_x0020_Web_x0020_ServicesSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://msds.diversey.com/MSDSWebService/jdimsds.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(JohnsonDiverseyX0020MSDSX0020WebX0020Services.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://msds.diversey.com/MSDSWebService/jdimsds.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public JohnsonDiverseyX0020MSDSX0020WebX0020Services(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public JohnsonDiverseyX0020MSDSX0020WebX0020Services(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JohnsonDiverseyX0020MSDSX0020WebX0020Services() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns JohnsonDiverseyX0020MSDSX0020WebX0020ServicesSoap
     */
    @WebEndpoint(name = "JohnsonDiversey_x0020_MSDS_x0020_Web_x0020_ServicesSoap")
    public JohnsonDiverseyX0020MSDSX0020WebX0020ServicesSoap getJohnsonDiverseyX0020MSDSX0020WebX0020ServicesSoap() {
        return super.getPort(JohnsonDiverseyX0020MSDSX0020WebX0020ServicesSoap, JohnsonDiverseyX0020MSDSX0020WebX0020ServicesSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JohnsonDiverseyX0020MSDSX0020WebX0020ServicesSoap
     */
    @WebEndpoint(name = "JohnsonDiversey_x0020_MSDS_x0020_Web_x0020_ServicesSoap")
    public JohnsonDiverseyX0020MSDSX0020WebX0020ServicesSoap getJohnsonDiverseyX0020MSDSX0020WebX0020ServicesSoap(WebServiceFeature... features) {
        return super.getPort(JohnsonDiverseyX0020MSDSX0020WebX0020ServicesSoap, JohnsonDiverseyX0020MSDSX0020WebX0020ServicesSoap.class, features);
    }

}
