package com.cleanwise.service.api.util;

/**
 * This class is the central location to store the internal 
 * JNDI names of various entities. Any change here should 
 * also be reflected in the deployment descriptors. 
 *
 * Copyright:   Copyright (c) 2001
 * Company:     CleanWise, Inc.
 * @author      Tim Besser
 *
 */

public interface JNDINames extends JNDINamesSuper{

  // 
  // JNDI names of EJB home objects
  //REMOVED COMES FROM AUTOGENERATED SUPER CLASS
  
  // 
  // JNDI Names of data sources.
  //
    public static final String 
	DATA_SOURCE = "java:/OracleDS",
	DATA_SOURCE_NO_TX = "java:/OracleDS_NO_TX",
	REPORT_DATA_SOURCE = "java:/ReportDS",
	ANALYTIC_DATA_SOURCE = "java:/AnalyticDS",
	STAGED_INFO_DATA_SOURCE = "java:/StagedInfoDS",
	JDINTEGRATION_DATA_SOURCE = "java:/JDIntegrationDS",
	MAIN_DATA_SOURCE = "java:/MainDS",
	STORE01_DATA_SOURCE = "java:/Store01DS",
	STORE02_DATA_SOURCE = "java:/Store02DS",
	STORE03_DATA_SOURCE = "java:/Store03DS",
	STORE04_DATA_SOURCE = "java:/Store04DS"	
	;

  //
  // JNDI Names of other resources.
  //

  //
  // JNDI Names of application properties.
  //
}
